import { getProviderModelName, PROVIDER_LABELS } from "../../constants/models";
import type {
  MessageMetadata,
  MistralAssistantContentChunk,
  Provider,
} from "../../types";

export const RESPONSE_PROVENANCE_MARKER_PREFIX = "[Response generated by ";

interface ProvenanceMessage {
  role: "user" | "assistant";
  content: string;
  model?: string | null;
  provider?: Provider | null;
  metadata?: MessageMetadata;
}

export function getResponseProvenanceLabel(
  message: Pick<ProvenanceMessage, "model" | "provider">,
) {
  if (!message.provider || !message.model) {
    return null;
  }

  return `${PROVIDER_LABELS[message.provider]} using ${getProviderModelName(
    message.provider,
    message.model,
  )}`;
}

export function getResponseProvenanceMarker(
  message: Pick<ProvenanceMessage, "model" | "provider">,
) {
  const label = getResponseProvenanceLabel(message);
  return label ? `${RESPONSE_PROVENANCE_MARKER_PREFIX}${label}]` : null;
}

function addMarkerToMistralContent(
  content: MistralAssistantContentChunk[],
  marker: string,
) {
  let lastTextIndex = -1;

  content.forEach((chunk, index) => {
    if (chunk.type === "text") {
      lastTextIndex = index;
    }
  });

  if (lastTextIndex < 0) {
    return content;
  }

  return content.map((chunk, index) =>
    index === lastTextIndex && chunk.type === "text"
      ? { ...chunk, text: `${marker}\n${chunk.text}` }
      : chunk,
  );
}

export function addResponseProvenanceToMessages<T extends ProvenanceMessage>(
  messages: T[],
): T[] {
  return messages.map((message) => {
    if (message.role !== "assistant") {
      return message;
    }

    const marker = getResponseProvenanceMarker(message);

    if (!marker || message.content.startsWith(RESPONSE_PROVENANCE_MARKER_PREFIX)) {
      return message;
    }

    const mistralAssistantContent =
      message.metadata?.providerState?.mistralAssistantContent;

    return {
      ...message,
      content: `${marker}\n${message.content}`,
      ...(mistralAssistantContent
        ? {
            metadata: {
              ...message.metadata,
              providerState: {
                ...message.metadata?.providerState,
                mistralAssistantContent: addMarkerToMistralContent(
                  mistralAssistantContent,
                  marker,
                ),
              },
            },
          }
        : {}),
    };
  });
}

export function buildResponseProvenanceInstruction(params: {
  currentModel?: string;
  currentProvider?: Provider;
}) {
  const currentLabel = getResponseProvenanceLabel({
    model: params.currentModel,
    provider: params.currentProvider,
  });
  const currentIdentity = currentLabel
    ? `The current response is being generated by ${currentLabel}. `
    : "";

  return `${currentIdentity}Earlier assistant messages may begin with a [Response generated by provider using model] marker. Treat each marker as authoritative provenance for that specific response and keep those identities distinct. Never claim that you generated, wrote, or previously stated content attributed to another provider or model. Do not repeat the markers or announce your current identity unless the user asks.`;
}
