export const SETTINGS_HEADER_TOP_PADDING = 22;
export const SETTINGS_HEADER_BOTTOM_PADDING = 18;
export const SETTINGS_HEADER_CONTROL_SIZE = 40;
export const SETTINGS_HEADER_HEIGHT =
  SETTINGS_HEADER_TOP_PADDING +
  SETTINGS_HEADER_BOTTOM_PADDING +
  SETTINGS_HEADER_CONTROL_SIZE;
export const SETTINGS_HERO_GLOW_HEIGHT =
  SETTINGS_HEADER_HEIGHT + 64;
